### ISSUE TITLE
Not working on Android Studio 3.3.2

### ISSUE THREAD

**Issue by FunkyMuse** [mhashim6/intellij-drumroll#1]
Using the Alpha version of this plugin but it isn't working.

Tried restarting the studio and still not working.

**Comment by mhashim6** [comment]
I'm limited by OpenAPI's (non-existing) documentation. I'll see if I can fix that.
Help is always appreciated.

**Comment by FunkyMuse** [comment]
Sorry my friend, the documentation is non-existent I could not help even tho i'm comfortable in Kotlin and the code you wrote is readable and simple...

I spent 30 minutes searching for documentation, shame that Jetbrains don't have documentation ....

**Comment by mhashim6** [comment]
This actually was my first plugin, and probably my last; I spent 4 hours just to figure out the right (non-deprecated) way to listen to compiler events. This api is a nightmare.

**Comment by mhashim6** [comment]
check e596e1aea608683af53b43cea0ab84f85e731d54 out.
it now works on android studio; but only the after-build sound effects, which means no drum-roll for now.
