### ISSUE TITLE
Breaks IDE

### ISSUE THREAD

**Issue by thesoviet-duck** [mhashim6/intellij-drumroll#10]
This just completely breaks the IDE and stops me from opening any project

**Comment by softwaresteph** [comment]
Same here. Just installed and then uninstalled immediately because it prevented me from opening any project. 
I'm running **Android Studio Iguana | 2023.2.1 Canary 1**

**Comment by mhashim6** [comment]
It must be another deprecated API from Jetbrains. I'll take a look.

**Comment by mhashim6** [comment]
A new update (2.1) is now being reviewed by JB. Will update the thread once approved inshallah.

**Comment by mhashim6** [comment]
[Released](https://plugins.jetbrains.com/plugin/12130-drum-roll).
