### ISSUE TITLE
Drumroll sound is fixed length

### ISSUE THREAD

**Issue by nlbuescher** [mhashim6/intellij-drumroll#2]
The drumroll sound does not last through the whole build step. It finishes before the build is complete.

**Comment by mhashim6** [comment]
I've not made my mind about that yet; build times _do_ get long, freezes are a common occurrence.
Just the thought of a 1+ minute of constant drum-roll-_ing_  is the pure definition of not-fun.

**Comment by OverZealous** [comment]
What about having the drum roll fade out slowly, so after ~30s or so it just goes away?

Maybe only start fading at 5-10s.

**Comment by nlbuescher** [comment]
@mhashim6 I would have thought that the drumroll continuing until the build is finished is a feature of the plugin, so that you have some sound to fill the void while compiling (like an auditory progress bar) :smile:

I'm personally not a fan of how the drumroll gets louder either

One other side effect is that if the build time is super short, like when you hit run again but didn't change any code, the drumroll continues well after the program has started

**Comment by mhashim6** [comment]
@nlbuescher, Yep I noticed that. Current implementation uses an mp3 file. So no tricks included.

**Comment by mhashim6** [comment]
I think you guys would like [v.02](https://github.com/mhashim6/intellij-drumroll/releases/tag/v0.2) .
