### ISSUE TITLE
Does not work for Gradle run configurations

### ISSUE THREAD

**Issue by nlbuescher** [mhashim6/intellij-drumroll#3]

**Comment by mhashim6** [comment]
I don't know if it's even possible to listen to gradle events, the OpenAPI documentation doesn't help.

**Comment by Maxr1998** [comment]
Hoping for that as well, I'm sure you can figure it out ^^
I love that plugin already!

**Comment by mhashim6** [comment]
Thanks, man!

**Comment by mhashim6** [comment]
check e596e1aea608683af53b43cea0ab84f85e731d54 out.
it now works on android studio; but only the after-build sound effects, which means no drum-roll for now.
