### ISSUE TITLE
How to build from src?

### ISSUE THREAD

**Issue by ColtonIdle** [mhashim6/intellij-drumroll#6]
I've built other plugins in the past via gradle, but I'm unsure how to build this from src.

**Comment by mhashim6** [comment]
This might be of help:
https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/using_dev_kit.html

**Comment by ColtonIdle** [comment]
I tried for about 4 hours and couldn't get it to build. 😭 

Under "Using DevKit" it says: "For new projects, it is recommend to use Gradle."

Do you think you could move this project to using gradle? It would also be helpful for people to contribute because building from src is easy and Android devs know gradle already.

Getting started with plugins with gradle
https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system.html

Tutorial to migrate old plugin to new gradle based plugin
https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html#adding-gradle-support-to-an-existing-devkit-based-intellij-platform-plugin

**Comment by mhashim6** [comment]
Yeah it can be a pain in the butt.
I’ve been willing to migrate to Gradle for a while, but never had the time though. It’s probably the first thing to do if I have to make an update in the future.

**Comment by ColtonIdle** [comment]
I'd be happy to work on the repo and any issues if you get it converted to gradle. I'll keep my eyes open. Thanks @mhashim6

**Comment by mhashim6** [comment]
> I'd be happy to work on the repo and any issues if you get it converted to gradle. I'll keep my eyes open. Thanks @mhashim6

You are welcome! And Thanks for your interest!
